### ISSUE TITLE
TypeError: AlacDecoder.setProperty is not a function

### ISSUE THREAD

**Issue by kclim2** [skerit/rudeplay#1]
node test.js 
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
/home/ubuntu/Downloads/rudeplay/lib/formats/alac_decoder_stream.js:55
AlacDecoder.setProperty('alac_default', {
            ^

TypeError: AlacDecoder.setProperty is not a function
    at Object.<anonymous> (/home/ubuntu/Downloads/rudeplay/lib/formats/alac_decoder_stream.js:55:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/Downloads/rudeplay/lib/init.js:80:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by skerit** [comment]
The DNS warning is normal, the `setProperty` error is not. I don't know what's missing. I'm currently working on version 0.2.0, though.
